export const GET_GIPHY_REQUEST = "GET_GIPHY_REQUEST";
export const GET_GIPHY_SUCCESS = "GET_GIPHY_SUCCESS";
export const GET_GIPHY_FAILURE = "GET_GIPHY_FAILURE";
export const CHANGE_GIF_NAVIGATION = "CHANGE_GIF_NAVIGATION";
export const CHANGE_GIF_SEARCH = "CHANGE_GIF_SEARCH";
